export const SET_ALERT = 'SET_ALERT';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_CART_SAGA = 'ADD_TO_CART_SAGA';
export const REMOVE_FROM_CART_SAGA = 'REMOVE_FROM_CART_SAGA';

export const FIND_EMPLOYEE = 'FIND_EMPLOYEE';
export const FIND_CUSTOMER = 'FIND_CUSTOMER';
